force-app/main/default/objects/Bar__mdt/Bar__mdt.object-meta.xml
<CustomObject>
    <label>Bar</label>
    <pluralLabel>Bars</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bar__mdt/fields/Foo__c.field-meta.xml
<CustomField>
    <fullName>Foo__c</fullName>
    <label>Foo</label>
    <referenceTo>Foo__mdt</referenceTo>
    <relationshipLabel>Bars</relationshipLabel>
    <relationshipName>Bars</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Foo__mdt/Foo__mdt.object-meta.xml
<CustomObject>
    <label>Foo</label>
    <pluralLabel>Foos</pluralLabel>
</CustomObject>

force-app/main/default/classes/Demo.cls
public with sharing class Demo {

	public static void noLimit() {
		dump([SELECT MasterLabel, (SELECT MasterLabel FROM Bars__r) FROM Foo__mdt ORDER BY MasterLabel]);
	}

	public static void withLimit(Integer theLimit) {
		dump([SELECT MasterLabel, (SELECT MasterLabel FROM Bars__r LIMIT :theLimit) FROM Foo__mdt ORDER BY MasterLabel]);
	}

	private static void dump(List<Foo__mdt> foos) {
		for(Foo__mdt foo : foos) {
			String message = 'Foo: ' + foo.MasterLabel + '\n';
			for(Bar__mdt bar : foo.Bars__r) {
				message += '\tChild Bar: ' + bar.MasterLabel + '\n';
			}
			System.debug(LoggingLevel.WARN, message);
		}
	}
}